// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UrbanRoadworks.Data;

#nullable disable

namespace UrbanRoadworks.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UrbanRoadworks.Models.RoadworkAsset", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("asset_type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Geometry>("geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<int?>("site_id")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.HasIndex("site_id");

                    b.ToTable("RoadworkAssets");
                });

            modelBuilder.Entity("UrbanRoadworks.Models.RoadworkRoad", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<Geometry>("geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("site_id")
                        .HasColumnType("integer");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("site_id");

                    b.ToTable("RoadworkRoads");
                });

            modelBuilder.Entity("UrbanRoadworks.Models.RoadworkSite", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("end_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Geometry>("geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("start_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.ToTable("RoadworkSites");
                });

            modelBuilder.Entity("UrbanRoadworks.Models.RoadworkAsset", b =>
                {
                    b.HasOne("UrbanRoadworks.Models.RoadworkSite", "Site")
                        .WithMany("Assets")
                        .HasForeignKey("site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("UrbanRoadworks.Models.RoadworkRoad", b =>
                {
                    b.HasOne("UrbanRoadworks.Models.RoadworkSite", "Site")
                        .WithMany("Roads")
                        .HasForeignKey("site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("UrbanRoadworks.Models.RoadworkSite", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("Roads");
                });
#pragma warning restore 612, 618
        }
    }
}
